import {StyleSheet} from 'react-native';
import {SW, SF, SH} from '../Utils';

export default StyleSheet.create({
  Container: {
    width: '100%',
    height: '100%',
    justifyContent: 'center',
    alignItems: 'center',
  },
  QoutetSyle: {
    fontSize: SF(17),
    color: '#800080',
    fontWeight: '600',
    textAlign: 'center',
    fontWeight: 400,
    paddingHorizontal: SW(10),
    paddingVertical: SH(5),
  },
  ViewBoxStyle: {
    // backgroundColor: '#fff',
    // padding: 10,
    width: '90%',
    alignSelf: 'center',
    borderWidth: SW(1),
    borderColor: '#800080',
    borderRadius: SW(10),
    marginVertical: SH(10),
    marginBottom: SH(40),
  },
  imagestyle: {
    width: SW(40),
    height: SW(40),
  },
  imagestyleright: {
    alignSelf: 'flex-end',
  },
  AuthorStyle: {
    fontSize: SF(16),
    fontWeight: 400,
    textAlign: 'right',
    paddingRight: SW(10),
    paddingBottom: SH(10),
    color: '#800080',
    paddingVertical: SH(5),
  },
  btnStyle: {
    borderWidth: SW(1),
    width: '45%',
    borderRadius: SW(50),
    paddingVertical: SH(10),
    justifyContent: 'center',
    alignItems: 'center',
    borderColor: '#000',
  },
  flexRowJuSpEq: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-evenly',
    marginBottom: SH(10),
  },
  BtnIcon: {
    width: SW(20),
    height: SH(20),
    tintColor: '#800080',
  },
  perousBtnStyle: {
    width: '45%',
    alignSelf: 'center',
    justifyContent: 'center',
    alignItems: 'center',
    paddingVertical: SH(10),
    backgroundColor: 'purple',
    borderRadius: SW(100),
    marginVertical: SH(20),
    overflow: 'hidden',
    shadowColor: '#d20845',
    shadowOffset: {
      width: 0,
      height: 12,
    },
    shadowOpacity: 0.23,
    shadowRadius: 12.81,
    elevation: 16,
  },
  genBtnStyle: {
    width: '45%',
    alignSelf: 'center',
    justifyContent: 'center',
    alignItems: 'center',
    // paddingVertical: SH(10),
    backgroundColor: 'purple',
    borderRadius: SW(100),
    marginVertical: SH(20),
    overflow: 'hidden',
    shadowColor: '#d20845',
    shadowOffset: {
      width: 0,
      height: 12,
    },
    shadowOpacity: 0.23,
    shadowRadius: 12.81,
    elevation: 16,
  },
  gradientBtn: {
    width: '100%',
    justifyContent: 'center',
    alignItems: 'center',
    paddingVertical: SH(10),
  },
  genBtnTextStyle: {
    fontSize: SF(17),
    color: '#fff',
    fontWeight: 600,
  },
  BtnView: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-evenly',
    position: 'absolute',
    width: '100%',
    bottom: SH(10)
  },
});
